# Generated by Django 5.0.3 on 2024-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('x', models.CharField(max_length=64)),
                ('y', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=64)),
            ],
        ),
    ]
