# Generated by Django 5.0.3 on 2024-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='x',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='y',
        ),
        migrations.AddField(
            model_name='loop',
            name='x1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='x2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='x3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='x4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='y1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='y2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='y3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loop',
            name='y4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loop',
            name='direction',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='loop',
            name='name',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
