# Generated by Django 5.0.3 on 2024-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_loop_x_remove_loop_y_loop_x1_loop_x2_loop_x3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=64)),
                ('address', models.CharField(default='-', max_length=64)),
                ('onwer', models.CharField(default='-', max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
