# Generated by Django 5.0.3 on 2024-03-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_onwer_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loops', to='tasks.task'),
        ),
    ]
